# -*- coding: utf-8 -*-
"""map_KMT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rtQxSgXdHk6VqvSuxbehlwfIMo6y431
"""

import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

# 创建部队撤退路线数据（基于维基百科信息）
troop_data = {
    'location': ['云南', '缅甸', '泰国', '老挝', '越南', '台湾'],
    'lat': [25.0, 21.0, 15.0, 18.0, 16.0, 23.5],
    'lon': [101.0, 96.0, 101.0, 105.0, 108.0, 121.0],
    'troop_units': [
        '第8军、第26军残部',
        '李弥兵团、第93师',
        '段希文部、第3军残部',
        '第5军残部',
        '黄杰兵团残部',
        '主力撤退至台湾'
    ],
    'year': [1950, 1950, 1951, 1951, 1950, 1949],
    'description': [
        '从云南边境撤退的国民党残军',
        '进入缅甸北部的国民党部队',
        '撤退至泰国北部的部队',
        '在老挝活动的残部',
        '从越南撤退的部队',
        '国民党主力撤退目的地'
    ]
}

df = pd.DataFrame(troop_data)

# 创建撤退路线连线数据
route_data = {
    'start_lat': [25.0, 25.0, 21.0, 21.0, 16.0],
    'start_lon': [101.0, 101.0, 96.0, 96.0, 108.0],
    'end_lat': [21.0, 16.0, 15.0, 18.0, 23.5],
    'end_lon': [96.0, 108.0, 101.0, 105.0, 121.0],
    'route_name': ['云南-缅甸', '云南-越南', '缅甸-泰国', '缅甸-老挝', '越南-台湾']
}

# 创建地图
fig = go.Figure()

# 添加撤退路线
for i in range(len(route_data['start_lat'])):
    fig.add_trace(go.Scattergeo(
        lon = [route_data['start_lon'][i], route_data['end_lon'][i]],
        lat = [route_data['start_lat'][i], route_data['end_lat'][i]],
        mode = 'lines',
        line = dict(width = 2, color = 'red'),
        opacity = 0.6,
        name = route_data['route_name'][i],
        hoverinfo = 'text',
        text = f"路线: {route_data['route_name'][i]}"
    ))

# 添加部队位置标记
fig.add_trace(go.Scattergeo(
    lon = df['lon'],
    lat = df['lat'],
    hoverinfo = 'text',
    text = df.apply(lambda row: f"位置: {row['location']}<br>部队: {row['troop_units']}<br>年份: {row['year']}<br>描述: {row['description']}", axis=1),
    mode = 'markers',
    marker = dict(
        size = 15,
        color = 'blue',
        opacity = 0.7,
        line = dict(width=2, color='darkblue')
    ),
    name = '国民党部队位置'
))

# 添加区域着色
region_data = [
    {'name': '云南边境', 'lat': [24.5, 24.5, 25.5, 25.5], 'lon': [100.5, 101.5, 101.5, 100.5]},
    {'name': '缅甸北部', 'lat': [20.0, 20.0, 22.0, 22.0], 'lon': [95.0, 97.0, 97.0, 95.0]},
    {'name': '泰国北部', 'lat': [14.0, 14.0, 16.0, 16.0], 'lon': [100.0, 102.0, 102.0, 100.0]},
    {'name': '老挝北部', 'lat': [17.0, 17.0, 19.0, 19.0], 'lon': [104.0, 106.0, 106.0, 104.0]},
    {'name': '越南北部', 'lat': [15.0, 15.0, 17.0, 17.0], 'lon': [107.0, 109.0, 109.0, 107.0]}
]

for region in region_data:
    fig.add_trace(go.Scattergeo(
        lon = region['lon'] + [region['lon'][0]],  # 闭合多边形
        lat = region['lat'] + [region['lat'][0]],
        mode = 'lines',
        fill = 'toself',
        fillcolor = 'rgba(255, 0, 0, 0.2)',
        line = dict(width=1, color='rgba(255, 0, 0, 0.5)'),
        name = region['name'],
        hoverinfo = 'text',
        text = f"区域: {region['name']}<br>国民党残军活动区域"
    ))

# 更新地图布局
fig.update_layout(
    title = dict(
        text = '国民党残余部队撤退至东南亚路线图 (1949-1951)',
        x = 0.5,
        xanchor = 'center',
        font = dict(size=20)
    ),
    geo = dict(
        scope = 'asia',
        showland = True,
        landcolor = 'rgb(243, 243, 243)',
        countrycolor = 'rgb(204, 204, 204)',
        showcountries = True,
        projection_type = 'mercator'
    ),
    width = 1000,
    height = 700
)

# 显示地图
fig.show()

# 添加数据表格显示
print("\n国民党残余部队撤退信息汇总:")
print("=" * 80)
for i, row in df.iterrows():
    print(f"位置: {row['location']:8} | 部队番号: {row['troop_units']:15} | 年份: {row['year']} | 描述: {row['description']}")